import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Nav = () => {
  return (
    <nav className="flex flex-col md:flex-row md:justify-around pt-8 items-center">
      <span></span>
      <ul className="flex space-x-16 text-2xl">
        <li>
          <a href="/work">
            Work
          </a>
        </li>
        <li>
          <a href="/about">
            About
          </a>
        </li>
        <li>
          <a href="/contact">
            Contact
          </a>
        </li>
      </ul>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
